<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="utf-8">
    <?= $this->headTitle();?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?= $this->BaseUrl();?>/css/bootstrap.css" rel="stylesheet">
     <link href="<?= $this->BaseUrl();?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?= $this->BaseUrl();?>/css/style.css" rel="stylesheet">
    <?php 
    $auth = Zend_Auth::getInstance();
      if ($auth->hasIdentity())  echo '<link href="'.$this->BaseUrl().'/css/userAdmin.css" rel="stylesheet">';
    ?>

    <style type="text/css">
    
      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
      
      /******************************************/
     
      #main-slider .item{
      height:500px;
      background:url('img/people.jpg') no-repeat;
      
      }  
      
      /*********************/
      #signPromo{
      	border-bottom:solid 1px #E5E9EC;
      	margin:30px auto 60px auto;
      }
      #signPromo h2{
      	color:#2E3133;
      }
       #signPromo p{
      	margin-bottom:40px;
      }
    
      /*********************/
      #custumersOpinion{
      	min-height: 300px;
		background-color:#F7F5F2;
		margin-top:80px;
		padding-top: 70px;
      }
      #custumersOpinion blockquote{
		border-left-width: 0px;
      }
      #custumersOpinion blockquote p{
      	font-style: italic;
  		font-family: Georgia, "Times New Roman", serif;
		font-size: 2.3em;
		text-indent: 20px;
		width: 500px;
		margin-left: 25px
      }
      #custumersOpinion blockquote small{
		font-size: 1.4em;
		text-align: right;
		margin-right: 80px;
      }
      #custumersOpinion blockquote span{
		font-size: 2.2em;
      }

      /*********************/
     .content{
        padding-top:75px;
      }
      #singUpBtn{
      	background-color:#4abfa5;padding:14px 40px 14px 40px;
      	box-shadow: 0px 2px 2px #888888;
      }
    </style>
   

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src=".././js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
	<link rel="shortcut icon" href="<?= $this->BaseUrl();?>/ico/favicon.png">
  </head>
<body>
 	<div class="header">
	 	 	<div id="logo">
				<img src="<?= $this->BaseUrl();?>/img/logo.png"/>
			</div> 
	 	 	<div id="menu-heder">
				<ul class="nav nav-pills pull-right">
					<li><a href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">Home</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">About</a></li>
					<li class="horizSeparator">|</li>
          <?php 
            
            if ($auth->hasIdentity()) {
              $identity=$auth->getIdentity();
            ?> 
                <li class="bordred">
                  <!-- Button to trigger modal -->
                  <a href="<?= $this->url(array('controller'=>'user','action'=>'index'));?>"><?=$identity->nom;?></a>
                </li>
                <li>
                  <!-- Button to trigger modal -->
                  <a href="<?= $this->url(array('controller'=>'user','action'=>'logout'));?>"> Log Out</a>
                </li>
             <?php   

           }else{
            ?>
                <li class="bordred">
                <!-- Button to trigger modal -->
                  <a href="#logInModal" id="loginMenuLink" data-toggle="modal">LogIn</a>
                </li>
                <li style="border-color:#70CCB7;"class="bordred">
                <!-- Button to trigger modal -->
                      <a href="<?= $this->url(array('controller'=>'index','action'=>'signin'));?>">Sign In</a>
                </li>

            <?php } ?>
          


					
				</ul>
			</div>
 	</div><!-- header -->

<div class="content">


	<?php echo $this->layout()->content; ?>


</div>

 <div class="footer">
 	<div class="row">
	 	<div class="span1 offset1 text-left">
	 		<h5>Menu</h5>
	 		<ul>
	 		<li><a href="#">Home</a></li>
	 		<li><a href="#">Contact</a></li>
	 		<li><a href="#">About</a></li>
	 		<li><a href="#">Sign In</a></li>
	 		</ul>
	 	</div>
	 	<div class="span1 offset1">
	 		<h5>Categories</h5>
	 		<ul>
	 		<li><a href="#">Enseignent</a></li>
	 		<li><a href="#">Entreprise</a></li>
	 		<li><a href="#">Project</a></li>
	 		<li><a href="#">Ecole</a></li>
	 		<li><a href="#">More ...</a></li>
	 		</ul>
	 	</div>
	 	<div class="span2 offset1">
	 		<h5>Sociale network</h5>
			<a href="#"><img src="<?= $this->BaseUrl();?>/img/fb.png" alt="faceBook"></a>
			<a href="#"><img src="<?= $this->BaseUrl();?>/img/twitter.png" alt="twitter"></a>
			<a href="#"><img src="<?= $this->BaseUrl();?>/img/rss.png" alt="RSS Feed"></a>
	 	</div>
 	</div>
	</div><!-- footer -->
    <?php 
      if (!$auth->hasIdentity()) {
    ?>
    <!-- Modal -->
    <div id="logInModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		    <h3 id="myModalLabel">Please Login </h3>
	    </div>
	  		<form id="loginForm"  action"<?= $this->url(array('controller'=>'index','action'=>'login'));?>" method="get">
	    		<div class="modal-body" >
		    		<label for="login">Username</label>
		    		<input name="login" id="login" type="text" class="" placeholder="login ..." class="input-xlarge" />
		    		<br/>
		    		<label for="password">Password</label>
		    		<input name="password" id="password" type="password" class="" placeholder="password ..." class="input-xlarge" /><br/>
		    		<a href="#" id="passwRecoInte" class="text-warning">Password Forgotten ?</a>

		    	</div>
				  <div id="logIncorrect" class="alert alert-error" style="margin:auto 10px 10px 10px;display:none;">
              <button type="button" class="close" aria-hidden="true">&times;</button>
              <strong>Login error!</strong> your login or/and password are incorrect.
          </div>
          <div id="logInactive" class="alert alert-error" style="margin:auto 10px 10px 10px;display:none;">
              <button type="button" class="close" aria-hidden="true">&times;</button>
              <strong>Login error!</strong> this account is not active yet, please check your email for an acctivation message from WebShop.
          </div>
          <div class="modal-footer" style="background-color:#FFF;padding-top:30px;">
				    <button class="btn flatBouton" style="background-color:#7ED1BE;background-image:none;" data-dismiss="modal" aria-hidden="true">Close</button>
				    <input type="submit" style="background-color:#FF9537;background-image:none;" value="Login" class="btn btn-primary flatBouton">
			    </div>
          <img class="ajaxLoader" src="<?= $this->BaseUrl();?>/img/ajaxLoader.gif" style="display:none;position:absolute;top:50%;left:20%;">
			</form>

      <form id="passRecovryForm" style="display:none;" action"<?= $this->url(array('controller'=>'index','action'=>'passwordrecovry'));?>" method="get">
          <div class="modal-body" >
            <label for="emailRecover">Enter your email</label>
            <input name="emailRecover" id="emailPassRecover" type="text" placeholder="email ..." class="input-xlarge" />
            <br/>
          </div>
          <div class="alert alert-error" style="margin:auto 10px 10px 10px;display:none;">
              <button type="button" class="close">&times;</button>
              <strong>Invalid email!</strong> this email is incorrect.
          </div>
          <div class="modal-footer" style="background-color:#FFF;padding-top:30px;">
            <input type="button" class="btn flatBouton" value="go back" id="prevtologin" style="background-color:#7ED1BE;background-image:none;"/>
            <button class="btn flatBouton" style="background-color:#7ED1BE;background-image:none;" data-dismiss="modal" aria-hidden="true">Close</button>
            <input type="submit" style="background-color:#FF9537;background-image:none;" value="Send me an email" class="btn btn-primary flatBouton"/>
          </div>
          <img class="ajaxLoader" src="<?= $this->BaseUrl();?>/img/ajaxLoader.gif" style="display:none;position:absolute;top:50%;left:20%;">
      </form>
      
    </div>
    <?php } ?> 
    <script src="<?= $this->BaseUrl();?>/js/jquery.js"></script>
    <script src="<?= $this->BaseUrl();?>/js/bootstrap.min.js"></script>

    <script type="text/javascript">
      <?php 
        if (!$auth->hasIdentity()) {
      ?>
     
      $("#loginForm").submit(function() {
        //alert('Handler for .submit() called.');
        $(this).fadeTo('slow', 0.3);
        $(this).children(".ajaxLoader").show();
        $.ajax({
              url:"<?= $this->url(array('controller'=>'index','action'=>'login'))?>",
              
              data:$(this).serialize(),
              type:'Get',//by default get
              success:function( msg ) {
                $("#loginForm .ajaxLoader").hide();
                $("#loginForm").fadeTo('fast', 1);
                $("#logInactive").hide();
                    $("#logIncorrect").hide();
                if(msg=='login succes'){
                  $('#logInModal').modal('hide');
                  window.location.replace("<?= $this->url(array('controller'=>'index','action'=>'index'))?>");

                }else{
                  $("#loginForm input[type=text]").css( "border-color", "#B94A48" );
                  $("#loginForm input[type=password]").css( "border-color", "#B94A48" );
                  if(msg=='not activeted')
                    $("#logInactive").show('slow');
                  else                    
                    $("#logIncorrect").show('slow');
                }
              },
              error:function( msg ) {
                alert( "Error : " + msg );
              }
            })
        return false;
      });

    $("#signInForm").submit(function() {
        $(this).fadeTo('slow', 0.5);
        $(this).children(".ajaxLoader").show();
        $.ajax({
              url:"<?= $this->url(array('controller'=>'index','action'=>'signin'))?>",
              data:$(this).serialize(),
              type:'Post',
              success:function( msg ) {
                $("#signInForm").children(".ajaxLoader").hide();
                $("#signInForm").fadeTo('fast', 1);
                $("#signInForm :input").each(function(){
                    $(this).parent('div').removeClass('error');
                    $(this).parent('div').children('span').hide();
                });
               $('#loginExiste').hide();
               $('#emailExiste').hide();
                var errorObject=JSON.parse(msg) ;
                if(errorObject.error.length>0){
                  if(errorObject.error[0]=='loginExiste'){
                    $('#loginExiste').show();
                    $('#login').parent('div').addClass('error');
                  }else if(errorObject.error[0]=='emailExiste' ){
                      $('#emailExiste').show();
                      $('#email').parent('div').addClass('error');
                  }else{
                   var index;
                  for (index = 0; index < errorObject.error.length; ++index) {
                    $('#'+errorObject.error[index]).parent('div').addClass('error');
                     $('#'+errorObject.error[index]).parent('div').children('span').show();
                    //console.log(index +' - '+errorObject.error[index]+'\n');
                  }
                }
                  
                }else
                   window.location.replace("<?= $this->url(array('controller'=>'index','action'=>'index'))?>");
              },
              error:function( msg ) {
                alert( "Error : " + msg );
              }
            })
        return false;
      });
      $("#passRecovryForm").on("submit",function() {
        $(this).fadeTo('slow', 0.7);
        $(this).children(".ajaxLoader").show();
        $.ajax({
              url:"<?= $this->url(array('controller'=>'index','action'=>'passwordrecovry'))?>",
              data:$(this).serialize(),
              type:'Get',
              success:function( msg ) {
                $("#passRecovryForm").children(".ajaxLoader").hide();
                $("#passRecovryForm").fadeTo('fast', 1);
                $("#passRecovryForm :input").each(function(){
                    $(this).parent('div').removeClass('error');
                    $(this).parent('div').children('span').hide();
                });
                   if(msg=='success recovry'){
                    window.location.replace("<?= $this->url(array('controller'=>'index','action'=>'passwordrecovry'))?>");
                   }else
                      $("#passRecovryForm .alert-error").show('slow');
                 },
              error:function( msg ) {
                alert( "Error : " + msg );
              }
            })
        return false;
      });
      $("#passwRecoInte").click(function(){
        $("#loginForm").hide();
        $("#passRecovryForm").fadeIn('slow');
        $("#myModalLabel").text("Password forgotten ");
      });

      $("#prevtologin").click(function(){
        $("#passRecovryForm").hide();
        $("#loginForm").fadeIn('slow');
        $("#myModalLabel").text("Please Login ");
      });

      $('#loginMenuLink').click(function(){
        //$("#loginForm button,#loginForm input").removeAttr('disabled');
        $("#loginForm").children(".ajaxLoader").hide();
        $("#loginForm").fadeTo('fast', 1);

        $("#passRecovryForm button,#passRecovryForm input").removeAttr('disabled');
        $("#passRecovryForm").children(".ajaxLoader").hide();
        $("#passRecovryForm").fadeTo('fast', 1);

        $("#passRecovryForm").hide();
        $("#loginForm").fadeIn('slow');
        $("#myModalLabel").text("Please Login ");
      });
      //////////////////////////////////////////
      $("#loginFormAdmin").submit(function() {
        //alert('Handler for .submit() called.');
        $(this).fadeTo('slow', 0.3);
        $(this).children(".ajaxLoader").show();
        $.ajax({
              url:"<?= $this->url(array('controller'=>'index','action'=>'adminlogin'))?>",
              
              data:$(this).serialize(),
              type:'Get',//by default get
              success:function( msg ) {
                $("#loginFormAdmin").children(".ajaxLoader").hide();
                $("#loginFormAdmin").fadeTo('fast', 1)
                if(msg=='login succes'){
                  window.location.replace("<?= $this->url(array('controller'=>'admin','action'=>'index'))?>");
                }else{
                  $("#loginFormAdmin input[type=text]").css( "border-color", "#B94A48" );
                  $("#loginFormAdmin input[type=password]").css( "border-color", "#B94A48" );
                  $("#loginFormAdmin .alert-error").show('slow');
                }
              },
              error:function( msg ) {
                alert( "Error : " + msg );
              }
            })
        return false;
      });
    $("#adminPasswRecoInte").click(function(){
        $("#loginFormAdmin").hide();
        $("#adminPassRecovryForm").fadeIn('slow');
        $("#loginAdmin .page-header").html("<h1>Recovry password <small>- Recovry password for Administrator of WebShop</small></h1>");
        return false;
      });
    $("#adminPrevtologin").click(function(){
        $("#adminPassRecovryForm").hide();
        $("#loginFormAdmin").fadeIn('slow');
        $("#loginAdmin .page-header").html("<h1>Login Form <small>- Login As Administrator of WebShop</small></h1>");
      });
    <?php }else{ ?>
      $("#userUpdate").on("submit",function() {
        var changed=false;
        $("#userUpdate input[type=text], #userUpdate input[type=password]").each(function(){
          if($(this).val()!="") changed=true;
        });

        if(changed){
           $("#userUpdate :input").each(function(){
                      $(this).parent('div').removeClass('error');
                      $(this).parent('div').children('span').hide();
            });
        $(this).fadeTo('slow', 0.7);
        $(this).children(".ajaxLoader").show();
        $.ajax({
              url:"<?= $this->url(array('controller'=>'user','action'=>'updateuser'))?>",
              data:$(this).serialize(),
              type:'post',
              success:function( msg ) {
                if(msg=="success"){
                  $("#userUpdate :input[type!=submit]").each(function(){
                    if(($(this).attr('id')!='email' || $(this).attr('id')!='login')&&$(this).val()!=''){
                      $(this).attr('placeholder',$(this).val());
                      $(this).val('');
                    }
                  });
                }else{
                  $("#userUpdate").children(".ajaxLoader").hide();
                  $("#userUpdate").fadeTo('fast', 1);
                 
                  var errorObject=JSON.parse(msg) ;
                  if(errorObject.error.length>0){
                     var index;
                    for (index = 0; index < errorObject.error.length; ++index) {
                      if(((errorObject.error[index]!='email' || errorObject.error[index]!='login') || errorObject.error[index]=="passwordConf")&& $('#'+errorObject.error[index]).val()!=''){
                        $('#'+errorObject.error[index]).parent('div').addClass('error');
                        $('#'+errorObject.error[index]).parent('div').children('span').show();
                      }
                      
                     }
                   }
                  }
               },
              error:function( msg ) {
                alert( "Error : " + msg );
              }
            })
        }  
        return false;
      });

       <?php } ?>
      $(".close").click(function(){
        $(this).parent(".alert").fadeOut('fast');
      });

    </script>
</body>
</html>