<div class="row-fluid">
    <div id="loginAdmin" class="span6 offset3">
      <div class="page-header">
            <h1>Login Form <small>- Login As Administrator of WebShop</small></h1>
      </div>
      <div class="row-fluid">
      <div class="span9 offset2">
			<form id="loginFormAdmin" style="" action"<?= $this->url(array('controller'=>'index','action'=>'adminlogin'));?>" method="get">
			    		<label for="login">Login</label>
			    		<input name="login" id="login" type="text" placeholder="login ..." class="input-xlarge" />
			    		<br/>
			    		<label for="password">Password</label>
			    		<input name="password" id="password" type="password" placeholder="password ..." class="input-xlarge" /><br/>
			    		<a href="<?= $this->url(array('controller'=>'admin','action'=>'adminlostpass'));?>" id="adminPasswRecoInte" class="text-warning">Password Forgotten ?</a>
				  <div class="alert alert-error" style="margin:auto 10px 10px 0px;display:none;">
		              <button type="button" class="close">&times;</button>
		              <strong>Login error!</strong> your login or/and password is incorrect.
		          </div>
		          <div class="row form-actions" style="background-color:#fff;">
		                <div class="span4 offset7">
		                  <input  type="submit" class="flatBouton btn-large btn-block" value="Submit"/>
		                </div>
		            </div>
		          <img class="ajaxLoader" src="<?= $this->BaseUrl();?>/img/ajaxLoader.gif" style="display:none;position:absolute;top:50%;left:40%;">
			</form>
      <form id="adminPassRecovryForm" style="display:none;"action"<?= $this->url(array('controller'=>'index','action'=>'adminlogin'));?>" method="get">
                    <label for="emailPassRecover">Enter your email</label>
            <input name="emailPassRecover" id="emailPassRecover" type="text" placeholder="email ..." class="input-xlarge" />
                    <br/>

                <div class="alert alert-error" style="margin:auto 10px 10px 0px;display:none;">
                    <button type="button" class="close">&times;</button>
                    <strong>Invalid email!</strong> this email is incorrect.
                </div>
                <div class="row form-actions" style="background-color:#fff;">
                  <div class="span8 offset5">
                    <input type="button" class="btn flatBouton" value="go back" id="adminPrevtologin" style="background-color:#7ED1BE;background-image:none;"/>
            <input type="submit" style="background-color:#FF9537;background-image:none;" value="Send me an email" class="btn btn-primary flatBouton"/>
                  </div>
                </div>
                    <img class="ajaxLoader" src="<?= $this->BaseUrl();?>/img/ajaxLoader.gif" style="display:none;position:absolute;top:50%;left:40%;">
            </form>
      	</div>
      </div>
		
	</div>
</div>