    <div id="main-slider" >
                <div id="mainSlider" class="carousel slide">
                    <ol class="carousel-indicators">
                    <li data-target="#mainSlider" data-slide-to="0" class="active"></li>
                    <li data-target="#mainSlider" data-slide-to="1"></li>
                    <li data-target="#mainSlider" data-slide-to="2"></li>
                    </ol>
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                        <div class="active item"></div>
                        <div class="item"></div>
                        <div class="item"></div>
                    </div>
                    <!-- Carousel nav -->
                    <a class="carousel-control left" href="#mainSlider" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#mainSlider" data-slide="next">&rsaquo;</a>
                </div>
    </div><!-- main-slider -->
    <div>
    
        <div id="signPromo" class="text-center">
            <h2>Build your amazing web sites NOW!</h2>
            <p class="lead muted">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <a id="singUpBtn" class="flatBouton" href="#">Sign up today</a>
            
        </div><!-- jumbotron -->
        <div id="services" class="row-fluid">
            <div>
                <div class="span3 offset1 text-left">
                    <h2 class="muted">Lorem</h2>
                    <p>
                    industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
                    </p>
                </div>
                <div class="span3 offset1 text-left">
                    <h2 class="muted">sheets</h2>
                    <p>
                    but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing L dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac c
                    </p>
                </div>
                <div class="span3 offset1 text-left">
                    <h2 class="muted">dapibus</h2>
                    <p>
                    s justo odio, dapibus ac facbut also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lilisis in, egestas eget quam. Fusce dapibus, tellus ac c
                    </p>
                </div>
            </div>
        </div><!-- row-fluid -->
    </div>
    <div id="custumersOpinion"  class="row-fluid">
    <div class="row-fluid">
        <span class="span1 offset3"><img src="./img/left_quote.png" alt="left quote"></span>
    </div>
    <div class="row-fluid">
           <blockquote class="span6 offset3">
            <p>Lorem ipsum dolor sit amet, consecteturLorem ipsum dolor  adipiscing elit. Integer posuere erat a ante.</p>
             <small>Someone famous <cite title="Source Title">Source Title</cite></small>
           </blockquote>
    </div>
    <div class="row-fluid">
        <span class="span1 offset8"><img src="./img/right_quote.png" alt="right quote"></span>
    </div>
          
    </div><!-- custumersOpinion -->