<div class="row">
		<div id="signPromo" class="text-center"  style="margin:100px auto 100px auto;">
            <h2>A new password has been send to your mail!</h2>
            <p class="lead muted">Check your mail .</p>
            <a id="singUpBtn" class="flatBouton" href="<?= $this->url(array('controller'=>'index','action'=>'index'))?>">Go to the Home page</a>
        </div><!-- jumbotron -->
</div>