    
<div class="row">
    <div id="inscriptionForm" class="span7 offset3">
      <div class="page-header">
            <h1>Sign Up Form  <small>- Account managment interface</small></h1>
      </div>
      <form>
        <fieldset>
          <!--<legend></legend>-->
          
            <div class="row">
               <div class="span3">
                <label for="login">Login</label>
                <input name="login" id="login" type="text" class"" placeholder="login ..." class="input-xlarge" />
                <label for="password">Password</label>
                <input name="password" id="password" type="text" placeholder="password ..." class="input-large" />
                <label for="passwordConf">Password Confirmation</label>
                <input name="passwordConf" id="passwordConf" type="text" placeholder="Password Confirmation ..." class="input-large" />
              </div>
              <div class="span3 offset1">
               <label for="lastName">Last Name</label>
                <input name="lastName" id="lastName" type="text" placeholder="Last Name ..." class="input-large" />
                 <label for="firstName">First Name</label>
                <input name="firstName" id="firstName" type="text" placeholder="First Name ..." class="input-large" />
                <label for="email">E-mail</label>
                <input name="email" id="email" type="text" class"" placeholder="E-mail ..." class="input-xlarge" />
              </div>
            </div>
            <div class="row form-actions">
                <div class="span2 offset5">
                  <input type="submit" class="flatBouton btn-large btn-block" value="Submit"/>
                </div>
            </div>
            
        </fieldset>
      </form>
    </div>  
</div> 